import { createContext, useContext, useState, useEffect } from "react";

const getStoredToken = () => {
  const token = localStorage.getItem("token");
  if (token) return token;

  try {
    const user = JSON.parse(localStorage.getItem("user") || "{}");
    return user?.token || "";
  } catch {
    return "";
  }
};

const LanguageContext = createContext(undefined);

const translations = {
  id: {
    // Common
    "common.back": "Kembali",
    "common.save": "Simpan",
    "common.cancel": "Batal",
    "common.delete": "Hapus",
    "common.edit": "Edit",
    "common.close": "Tutup",
    "common.search": "Cari",
    "common.loading": "Memuat...",
    "common.error": "Terjadi kesalahan",
    "common.login": "Masuk",
    "common.register": "Daftar",
    "common.email": "Email",
    "common.password": "Kata sandi",
    "common.name": "Nama",
    "common.upgrade": "Upgrade",
    "common.unlimited": "Tanpa batas",
    "common.page_of": "Halaman {{current}} dari {{total}}",
    "common.prev": "Sebelumnya",
    "common.next": "Berikutnya",
    "common.version": "Versi",
    "auth.login_subtitle": "Masuk ke akun Anda",
    "auth.forgot_password": "Lupa Password?",
    "auth.login_failed": "Login gagal",
    "auth.google_login_failed": "Login Google gagal",
    "auth.or_continue": "Atau lanjutkan dengan",
    "auth.login_google": "Masuk dengan Google",
    "auth.no_account": "Belum punya akun?",
    "auth.register_now": "Daftar Sekarang",
    "auth.register_title": "Daftar Akun Baru",
    "auth.register_subtitle": "Mulai petualangan kuliner Anda",
    "auth.full_name": "Nama Lengkap",
    "auth.name_placeholder": "Nama Anda",
    "auth.password_placeholder": "Min. 8 karakter",
    "auth.server_failed": "Gagal terhubung ke server",
    "auth.or_register": "Atau daftar dengan",
    "auth.register_google": "Daftar dengan Google",
    "auth.agree_prefix": "Dengan mendaftar, Anda menyetujui",
    "auth.agree_suffix": "kami",
    "auth.have_account": "Sudah punya akun?",
    "onboarding.skip": "Lewati",
    "onboarding.swipe": "Geser untuk lanjut",
    "onboarding.start": "Mulai",
    "onboarding.slide1.title": "Foto Bahan Masakanmu",
    "onboarding.slide1.desc": "Kamu bingung mau makan apa hari ini? Foto saja bahan masakanmu, biar kami siapkan resepnya!",
    "onboarding.slide2.title": "Dapatkan Resep Instan",
    "onboarding.slide2.desc": "Dapatkan beberapa pilihan resep praktis, lengkap dengan kalori & nutrisi.",
    "onboarding.slide2.highlight": "Sup • Tumis • Goreng",
    "onboarding.slide3.title": "Masak & Belanja Pintar",
    "onboarding.slide3.desc": "Ikuti langkah masaknya, beli bahan yang kurang lewat link Shopee.",
    "messages.title": "Pesan",
    "messages.search": "Cari obrolan...",
    "messages.cooking_friends": "Teman Memasak",
    "messages.loading_friends": "Memuat teman...",
    "messages.no_other_friends": "Tidak ada teman lain",
    "messages.recent_chats": "Obrolan Terakhir",
    "messages.loading_chats": "Memuat obrolan...",
    "messages.no_history": "Belum ada riwayat pesan.",
    "messages.cooking_friend": "Teman Masak",
    "messages.no_message": "Belum ada pesan",
    "chat.group_name": "Grup Masak Bareng",
    "chat.group": "Grup",
    "chat.online": "Online",
    "chat.offline": "Offline",
    "chat.search_messages": "Cari pesan...",
    "chat.loading": "Memuat chat...",
    "chat.no_history": "Belum ada riwayat obrolan.",
    "chat.upload_failed": "Gagal upload gambar",
    "chat.send_failed": "Gagal mengirim pesan",
    "chat.image_only": "Hanya file gambar",
    "chat.ready_to_send": "Siap dikirim",
    "chat.caption_placeholder": "Tambahkan keterangan... (opsional)",
    "chat.message_placeholder": "Ketik pesan...",
    "post.share_title": "Bagikan Masakan Anda",
    "post.photo": "Foto Masakan *",
    "post.upload_photo": "Ambil atau Upload Foto",
    "post.recipe_name": "Nama Masakan *",
    "post.recipe_placeholder": "Contoh: Nasi Goreng Special",
    "post.description": "Deskripsi (Opsional)",
    "post.description_placeholder": "Ceritakan tentang masakan ini...",
    "post.who_can_see": "Siapa yang bisa lihat?",
    "post.public_desc": "Semua orang bisa lihat",
    "post.friends_desc": "Hanya teman yang bisa lihat",
    "post.private": "Privat",
    "post.private_desc": "Hanya saya yang bisa lihat",
    "post.required": "Nama resep dan foto wajib diisi!",
    "feedback.choose_category": "Pilih kategori feedback",
    "feedback.write_feedback": "Tulis feedback Anda",
    "feedback.thanks": "Terima kasih atas feedback Anda!",
    "feedback.title": "Kirim Feedback",
    "feedback.experience": "Bagaimana pengalaman Anda?",
    "feedback.category": "Kategori",
    "feedback.detail": "Ceritakan lebih detail",
    "feedback.placeholder": "Tulis feedback, saran, atau laporan bug Anda di sini...",
    "feedback.characters": "{{count}}/500 karakter",
    "feedback.bug": "Bug Report",
    "feedback.feature": "Fitur Baru",
    "feedback.improvement": "Saran Perbaikan",
    "feedback.other": "Lainnya",
    "not_found.title": "Halaman Tidak Ditemukan",
    "not_found.desc": "Ups! Sepertinya resep yang Anda cari tidak ada di dapur kami.",
    "payment.verifying": "Memverifikasi pembayaran...",
    "payment.wait": "Mohon Tunggu",
    "payment.order_missing": "Order ID tidak ditemukan",
    "payment.token_missing": "Token login tidak ditemukan. Silakan login ulang.",
    "payment.not_success": "Pembayaran belum berhasil",
    "payment.success_message": "Pembayaran berhasil! Akun Premium sudah aktif.",
    "payment.verify_failed": "Gagal memverifikasi pembayaran",
    "payment.active": "Premium Aktif",
    "payment.view_account": "Lihat Akun",
    "payment.failed": "Verifikasi Gagal",
    "payment.back_premium": "Kembali ke Premium",
    "scan_history.title": "Riwayat Scan",
    "scan_history.search": "Cari berdasarkan bahan...",
    "scan_history.loading": "Memuat riwayat...",
    "scan_history.load_error": "Gagal memuat riwayat scan.",
    "scan_history.deleted": "Riwayat scan berhasil dihapus",
    "scan_history.delete_error": "Gagal menghapus item riwayat",
    "scan_history.cleared": "Semua riwayat berhasil dikosongkan",
    "scan_history.clear_error": "Gagal mengosongkan riwayat",
    "scan_history.recipe_options": "{{count}} pilihan resep",
    "scan_history.empty": "Tidak ada riwayat ditemukan",
    "scan_history.delete_all": "Hapus Semua Riwayat",
    "comments.title": "Komentar",
    "comments.added": "Komentar berhasil ditambahkan!",
    "comments.confirm_delete": "Apakah Anda yakin ingin menghapus komentar ini?",
    "comments.deleted": "Komentar berhasil dihapus!",
    "comments.empty": "Belum ada komentar",
    "comments.be_first": "Jadilah yang pertama berkomentar!",
    "comments.edit_placeholder": "Edit komentar Anda...",
    "comments.write_placeholder": "Tulis komentar...",
    "comments.just_now": "Baru saja",
    "comments.minutes_ago": "{{count}} menit lalu",
    "comments.hours_ago": "{{count}} jam lalu",
    "comments.days_ago": "{{count}} hari lalu",
    "recipe.ai_recommendation": "Rekomendasi AI",
    "recipe.removed_substitution": "Batal mengganti {{name}}",
    "recipe.back_original": "Kembali ke bahan asli",
    "recipe.removed_cookbook": "Dihapus dari Cookbook",
    "recipe.saved_cookbook": "Disimpan ke Cookbook!",
    "recipe.share_success": "Link resep disalin! Bagikan ke WhatsApp",
    "recipe.login_first": "Anda harus login terlebih dahulu",
    "recipe.added_cart": "{{name}} ditambahkan ke keranjang",
    "recipe.add_shopping_failed": "Gagal menambah ke daftar belanja",
    "recipe.tweaker_premium": "AI Taste Tweaker adalah fitur Premium! Upgrade untuk mengakses.",
    "recipe.premium_only": "Khusus Premium",
    "recipe.tweaking": "AI sedang mengubah resep...",
    "recipe.tweak_failed": "AI gagal memproses",
    "recipe.tweaker_desc": "Ubah resep sesuai selera Anda",
    "recipe.tweaker_desc_locked": "Premium - Ubah resep sesuai selera Anda",
    "recipe.spicier": "Bikin Lebih Pedas",
    "recipe.less_sugar": "Bikin Versi Rendah Gula",
    "recipe.healthier": "Bikin Lebih Sehat",
    "recipe.no_chili": "Bikin Tanpa Cabai",
    "recipe.less_spicy": "Kurangi Pedasnya",
    "recipe.custom_pref": "Atau tulis preferensi sendiri",
    "recipe.custom_placeholder": "Contoh: Bikin versi tanpa MSG",
    "recipe.change_recipe": "Ubah Resep",
    "recipe.replaced_with": "Diganti dengan:",
    "recipe.ratio": "Rasio {{ratio}}",
    "recipe.cooking_steps": "Cara Memasak",
    "recipe.step": "Langkah {{count}}",
    "recipe.ask_ai": "Tanya AI Sous-Chef",
    "recipe.ask_example": "\"Kalau gak ada saus tiram, bisa diganti apa?\"",
    "recipe.question_placeholder": "Tulis pertanyaan Anda...",
    "recipe.send": "Kirim",
    "recipe.selected_rating": "Anda memilih rating {{rating}} bintang",
    "recipe.save_rating": "Simpan Rating",
    "recipe.confirm_rating": "Apakah Anda yakin memberi rating {{rating}} bintang?",
    "recipe.yes_save": "Ya, Simpan",
    "recipe.rating_saved": "Rating {{rating}} bintang tersimpan",
    "recipe.rating_saved_db": "Rating {{rating}} bintang berhasil disimpan ke database!",
    "recipe.rating_save_failed": "Gagal menyimpan rating ke database: {{message}}",
    "recipe.thanks_feedback": "Terima kasih atas feedback Anda!",
    "weekly.title": "Ringkasan Mingguan",
    "weekly.recipes_made": "Resep Dibuat",
    "weekly.saved_recipes": "Resep Disimpan",
    "weekly.top_ingredients": "Bahan Paling Sering Digunakan",
    "weekly.used_count": "Digunakan {{count}}x",
    "weekly.no_cooking": "Belum ada riwayat memasak minggu ini",
    "weekly.achievements": "Pencapaian Minggu Ini",
    "weekly.no_achievements": "Belum ada pencapaian minggu ini",
    "payment.phone_required": "Masukkan nomor telepon Anda",
    "payment.notification_phone": "Notifikasi pembayaran akan dikirim ke nomor ini",
    "payment.select_va_transfer": "Pilih menu Transfer ke Virtual Account",
    "payment.enter_va": "Masukkan nomor VA di atas",
    "payment.transfer_amount": "Transfer sejumlah {{amount}}",
    "payment.save_proof": "Simpan bukti transfer",
    "payment.continue_agree": "Dengan melanjutkan, Anda menyetujui",
    "payment.premium_active_package": "Paket Premium Aktif",
    "payment.valid_until": "Berlaku hingga 10 Mei 2026",
    "common.confirm": "Konfirmasi",
    
    // Home Screen
    "home.greeting.morning": "Selamat Pagi",
    "home.greeting.afternoon": "Selamat Siang",
    "home.greeting.evening": "Selamat Malam",
    "home.scan_prompt": "Apa yang ingin kamu masak hari ini?",
    "home.scan_button": "Scan Bahan",
    "home.quick_recipes": "Resep Cepat",
    "home.saved_recipes": "Resep Tersimpan",
    "home.recent_scans": "Scan Terakhir",
    "home.view_all": "Lihat Semua",
    "home.ingredients": "bahan",
    "home.no_saved_recipes": "Belum ada resep tersimpan",
    "home.start_scanning": "Mulai scan untuk menemukan resep!",
    "home.guest": "Tamu",
    "home.daily_search": "Pencarian hari ini",
    "home.upgrade_unlimited": "Upgrade untuk scan tanpa batas",
    "home.premium_active": "Premium aktif - scan tanpa batas",
    "home.scan_card_title": "Foto Bahan Dapur Anda",
    "home.scan_card_desc": "AI akan mengenali bahan dan membuat resep untuk Anda",
    "home.sending_image": "Mengirim gambar ke server...",
    "home.open_camera": "Buka Kamera",
    "home.take_photo": "Jepret",
    "home.upload": "Upload",
    "home.cooking_gallery": "Galeri Masakan",
    "home.history": "Riwayat",
    "home.latest_results": "{{count}} hasil terakhir",
    "home.no_scan_history": "Belum ada riwayat scan",
    "home.recipes_generated": "{{count}} resep dihasilkan",
    "home.public_cooking_count": "{{count}} masakan publik",
    "home.friends_cooking_count": "{{count}} masakan dari teman",
    "home.my_cooking_count": "{{count}} masakan Anda",
    "home.share": "Bagikan",
    "home.public": "Publik",
    "home.friends": "Teman",
    "home.me": "Saya",
    "home.no_shared_cooking": "Belum ada masakan yang dibagikan",
    "home.no_friends_cooking": "Belum ada masakan dari teman",
    "home.no_my_cooking": "Belum ada masakan yang Anda bagikan",
    "home.share_first_cooking": "Bagikan Masakan Pertama",
    "home.camera_permission_denied": "Izin kamera ditolak",
    "home.camera_not_found": "Kamera tidak ditemukan",
    "home.camera_busy": "Kamera sedang digunakan aplikasi lain",
    "home.camera_access_error": "Tidak bisa akses kamera",
    "home.analyzing_food": "Menganalisis masakan...",
    "home.scan_done": "Scan selesai!",
    "home.invalid_backend_response": "Respons backend tidak valid. Silakan coba lagi.",
    "home.process_image_error": "Terjadi kesalahan saat memproses gambar",
    "home.daily_limit_reached": "Limit scan harian tercapai!",
    "home.camera_not_ready": "Kamera belum siap",
    "home.image_only": "File harus berupa gambar",
    "home.post_shared": "Masakan berhasil dibagikan!",
    "home.post_deleted": "Masakan berhasil dihapus!",
    "home.privacy_changed": "Privasi diubah ke {{label}}",
    
    // Scan Result
    "scan.detected_ingredients": "Bahan Terdeteksi",
    "scan.add_ingredient": "Tambah Bahan",
    "scan.ingredient_placeholder": "Ketik nama bahan...",
    "scan.generating": "AI sedang membuat resep untukmu...",
    "scan.recipe_recommendations": "Rekomendasi Resep",
    "scan.view_recipe": "Lihat Resep",
    "scan.title": "Hasil Scan",
    "scan.no_data": "Tidak ada data resep yang diterima. Silakan kembali ke Home.",
    "scan.analyzing": "AI sedang menganalisis...",
    "scan.analyzing_desc": "Mengenali bahan dan meracik resep terbaik",
    "scan.no_specific_ingredients": "Tidak ada bahan spesifik yang terdeteksi secara otomatis.",
    "scan.recipe_options": "Beberapa Pilihan Resep Untukmu",
    "scan.ai_recipe": "Resep AI",
    "scan.calories": "Kalori",
    "scan.protein": "Protein",
    "scan.carbs": "Karbo",
    "scan.time": "Waktu",
    "scan.preparing_recipe": "Menyiapkan Resep...",
    "scan.save_view_recipe": "Simpan & Lihat Resep",
    "scan.save_failed": "Gagal menyimpan resep: {{message}}",
    
    // Recipe Detail
    "recipe.ingredients": "Bahan-Bahan",
    "recipe.instructions": "Cara Membuat",
    "recipe.nutrition": "Informasi Nutrisi",
    "recipe.start_cooking": "Mulai Memasak",
    "recipe.save": "Simpan",
    "recipe.saved": "Tersimpan",
    "recipe.add_to_shopping": "Tambah ke Belanja",
    "recipe.servings": "Porsi",
    "recipe.cook_time": "Waktu Masak",
    "recipe.difficulty.easy": "Mudah",
    "recipe.difficulty.medium": "Sedang",
    "recipe.difficulty.hard": "Sulit",
    "recipe.calories": "Kalori",
    "recipe.protein": "Protein",
    "recipe.carbs": "Karbo",
    "recipe.time": "Waktu",
    
    // Cooking Mode
    "cooking.step": "Langkah",
    "cooking.previous": "Sebelumnya",
    "cooking.next": "Selanjutnya",
    "cooking.finish": "Selesai",
    "cooking.timer": "Timer",
    "cooking.start_timer": "Mulai Timer",
    "cooking.complete_title": "Selamat! 🎉",
    "cooking.complete_message": "Kamu berhasil menyelesaikan resep ini",
    "cooking.rate_recipe": "Beri Rating",
    "cooking.back_home": "Kembali ke Home",
    "cooking.mode": "Mode Memasak",
    "cooking.step_of": "Langkah {{current}} dari {{total}}",
    "cooking.completed_toast": "Selamat! Masakan Anda selesai!",
    "cooking.timer_done": "Timer selesai!",
    "cooking.timer_done_desc": "Lanjut ke langkah berikutnya",
    "cooking.substitution_notice": "Gunakan bahan pengganti untuk langkah ini:",
    "cooking.ratio": "Rasio {{ratio}}",
    "cooking.ingredients_for_step": "Bahan untuk Langkah Ini:",
    "cooking.beginner_tips": "Tips untuk Pemula:",
    "cooking.step_done": "Langkah selesai!",
    "cooking.continue": "Lanjut",
    "cooking.ask_about_step": "Ada yang ingin ditanyakan tentang langkah ini?",
    "cooking.question_time": "\"Berapa lama harus ditumis?\"",
    "cooking.question_substitute": "\"Bisa ganti bahan ini?\"",
    
    // Cookbook
    "cookbook.title": "Buku Resep",
    "cookbook.all": "Semua",
    "cookbook.breakfast": "Sarapan",
    "cookbook.lunch": "Makan Siang",
    "cookbook.dinner": "Makan Malam",
    "cookbook.snack": "Camilan",
    "cookbook.empty": "Belum ada resep tersimpan",
    "cookbook.start_exploring": "Mulai eksplorasi resep!",
    "cookbook.my_title": "Cookbook Saya",
    "cookbook.halal": "Halal",
    "cookbook.vegetarian": "Vegetarian",
    "cookbook.vegan": "Vegan",
    "cookbook.favorite": "Favorit",
    "cookbook.newest": "Terbaru",
    "cookbook.empty_title": "Cookbook Masih Kosong",
    "cookbook.empty_desc": "Simpan resep favorit Anda di sini",
    "cookbook.start_scan": "Mulai Scan Sekarang",
    "cookbook.confirm_delete": "Yakin ingin menghapus resep ini dari Cookbook?",
    "cookbook.delete_success": "Resep berhasil dihapus!",
    "cookbook.delete_error": "Gagal menghapus resep.",
    
    // Shopping List
    "shopping.title": "Daftar Belanja",
    "shopping.add_item": "Tambah Item",
    "shopping.item_placeholder": "Nama bahan...",
    "shopping.clear_completed": "Hapus Selesai",
    "shopping.empty": "Daftar belanja kosong",
    "shopping.add_ingredients": "Tambah bahan yang dibutuhkan",
    "shopping.buy_all_shopee": "Beli Semua di Shopee",
    "shopping.buy": "Beli",
    "shopping.shopee_info_title": "Belanja Mudah di Shopee",
    "shopping.shopee_info_desc": "Klik tombol \"Beli\" untuk langsung mencari produk di aplikasi Shopee. Gratis ongkir untuk pembelian tertentu!",
    "shopping.unchecked_count": "{{count}} item belum dibeli",
    "shopping.find_recipe": "Cari Resep",
    "shopping.load_error": "Gagal memuat daftar belanja",
    "shopping.login_first": "Silahkan login terlebih dahulu",
    "shopping.update_error": "Gagal memperbarui",
    "shopping.add_error": "Gagal menambah bahan",
    "shopping.deleted": "Item dihapus dari daftar belanja",
    "shopping.delete_error": "Gagal menghapus: {{message}}",
    "shopping.connection_error": "Kesalahan koneksi ke server",
    "shopping.shopee_info_short": "Klik tombol \"Beli\" untuk langsung mencari produk di aplikasi Shopee.",
    
    // Account
    "account.title": "Akun",
    "account.free_plan": "Paket Gratis",
    "account.premium_plan": "Premium",
    "account.upgrade": "Upgrade ke Premium",
    "account.scans_left": "scan tersisa hari ini",
    "account.unlimited_scans": "Scan Unlimited",
    "account.edit_profile": "Edit Profil",
    "account.dietary_preferences": "Preferensi Diet",
    "account.scan_history": "Riwayat Scan",
    "account.settings": "Pengaturan",
    "account.send_feedback": "Kirim Feedback",
    "account.help": "Bantuan & Dukungan",
    "account.logout": "Keluar",
    "account.guest": "Tamu",
    "account.current_plan": "Paket Saat Ini",
    "account.active_until": "Aktif sampai {{date}}",
    "account.your_stats": "Statistik Anda",
    "account.scan": "Scan",
    "account.recipes": "Resep",
    "account.cooking": "Masakan",
    "account.change_preferences": "Ubah Preferensi",
    "account.light_mode": "Mode Terang",
    "account.dark_mode": "Mode Gelap",
    "account.name_placeholder": "Nama Anda",
    "account.stats_error": "Gagal mengambil statistik. Silakan coba lagi.",
    "account.logout_success": "Berhasil keluar",
    "account.name_limit_error": "Anda sudah mengubah nama sekali. Upgrade ke Premium untuk ubah nama tanpa batas!",
    "account.name_empty": "Nama tidak boleh kosong",
    "account.name_changed": "Nama berhasil diubah",
    "account.name_changed_free": "Nama berhasil diubah. Anda tidak dapat mengubah nama lagi kecuali upgrade ke Premium.",
    "account.confirm_name_title": "Konfirmasi Perubahan Nama",
    "account.confirm_name_premium": "Apakah Anda yakin ingin mengubah nama Anda?",
    "account.confirm_name_free": "Apakah Anda yakin ingin mengubah nama Anda? Sebagai pengguna gratis, Anda hanya dapat mengubah nama sekali.",
    "account.confirm_change": "Ya, Ubah",
    
    // Settings
    "settings.title": "Pengaturan",
    "settings.notifications": "Notifikasi",
    "settings.recipe_recommendations": "Rekomendasi Resep",
    "settings.shopping_reminder": "Pengingat Belanja",
    "settings.weekly_digest": "Ringkasan Mingguan",
    "settings.promotions": "Promosi & Penawaran",
    "settings.language": "Bahasa",
    "settings.indonesian": "Bahasa Indonesia",
    "settings.english": "English",
    "settings.data_privacy": "Data & Privasi",
    "settings.auto_save": "Simpan Otomatis",
    "settings.export_data": "Ekspor Data",
    "settings.delete_account": "Hapus Akun",
    "settings.help_support": "Bantuan & Dukungan",
    "settings.help_center": "Pusat Bantuan",
    "settings.terms": "Syarat & Ketentuan",
    "settings.privacy": "Kebijakan Privasi",
    "settings.app_preferences": "Preferensi Aplikasi",
    "settings.recipe_recommendations_desc_short": "Terima saran resep harian",
    "settings.shopping_reminder_desc_short": "Notifikasi daftar belanja",
    "settings.weekly_digest_desc_short": "Statistik mingguan Anda",
    "settings.promotions_tips": "Promosi & Tips",
    "settings.promotions_tips_desc": "Penawaran dan tips memasak",
    "settings.language_desc_short": "Pilih bahasa aplikasi",
    "settings.auto_save_recipe": "Auto-save Resep",
    "settings.auto_save_recipe_desc": "Simpan otomatis resep yang dilihat",
    "settings.export_data_desc_short": "Unduh semua data Anda",
    "settings.backup_data": "Backup Data",
    "settings.backup_data_desc": "Simpan data ke cloud",
    "settings.clear_cache": "Hapus Cache",
    "settings.clear_cache_desc": "Bersihkan data sementara",
    "settings.help_center_desc_short": "FAQ dan panduan",
    "settings.terms_desc_short": "Baca syarat penggunaan",
    "settings.privacy_desc_short": "Pelajari privasi Anda",
    "settings.danger_zone": "Zona Berbahaya",
    "settings.danger_desc": "Tindakan ini bersifat permanen dan tidak dapat dibatalkan.",
    "settings.export_success": "Data berhasil diekspor",
    "settings.delete_coming_soon": "Fitur hapus akun akan segera hadir",
    "settings.contact_support": "Hubungi support untuk bantuan",
    "settings.backup_success": "Backup berhasil dibuat",
    "settings.cache_cleared": "Cache berhasil dihapus",
    "settings.weekly_enabled": "Ringkasan mingguan diaktifkan!",
    "settings.weekly_enabled_desc": "Klik untuk lihat contoh ringkasan",
    "settings.view": "Lihat",
    
    // Premium
    "premium.title": "Upgrade ke Premium",
    "premium.subtitle": "Nikmati fitur lengkap SnapChef AI",
    "premium.monthly": "Bulanan",
    "premium.yearly": "Tahunan",
    "premium.save": "Hemat 40%",
    "premium.per_month": "/bulan",
    "premium.per_year": "/tahun",
    "premium.start_trial": "Coba Gratis 7 Hari",
    "premium.subscribe": "Berlangganan",
    "premium.feature.scans": "Scan Unlimited",
    "premium.feature.recipes": "Simpan Unlimited Resep",
    "premium.feature.rename": "Ubah Nama Unlimited",
    "premium.feature.premium_recipes": "Akses Resep Premium",
    "premium.feature.support": "Prioritas Customer Support",
    "premium.feature.ad_free": "Bebas Iklan",
    "premium.hero_title": "SnapChef Premium",
    "premium.hero_desc": "Nikmati pengalaman memasak tanpa batas dengan AI yang lebih pintar",
    "premium.already_premium": "Anda sudah Premium!",
    "premium.not_logged_in": "Anda belum login",
    "premium.price": "Rp 49.000",
    "premium.payment_via": "Bayar mudah via Midtrans",
    "premium.no_daily_limit": "Tidak ada batasan scan harian",
    "premium.chat_title": "AI Chat Sous-Chef Premium",
    "premium.chat_desc": "Tanya jawab tidak terbatas dengan AI",
    "premium.taste_title": "AI Taste Tweaker",
    "premium.taste_desc": "Ubah resep sesuai selera (pedas, diet, dll)",
    "premium.vision_title": "AI Vision Advanced",
    "premium.vision_desc": "Deteksi bahan lebih akurat & cepat",
    "premium.exclusive_recipes": "Resep Eksklusif",
    "premium.exclusive_recipes_desc": "Akses ribuan resep premium",
    "premium.process": "Memproses...",
    "premium.upgrade_now": "Upgrade Sekarang",
    "premium.already_button": "Sudah Premium",
    "premium.payment_methods": "Metode Pembayaran",
    "premium.package_comparison": "Perbandingan Paket",
    "premium.daily_scan": "Scan Harian",
    "premium.free_scan": "3 scan/hari",
    "premium.limited": "Terbatas",
    "premium.disclaimer_1": "Dengan melakukan upgrade, Anda menyetujui",
    "premium.disclaimer_2": "kami",
    "premium.cancel_anytime": "Berlangganan dapat dibatalkan kapan saja",
    "premium.login_required": "Anda harus login terlebih dahulu!",
    "premium.transaction_failed": "Gagal membuat transaksi",
    "premium.payment_open_failed": "Gagal membuka pembayaran Midtrans",
    
    // Navigation
    "nav.home": "Home",
    "nav.cookbook": "Resep",
    "nav.shopping": "Belanja",
    "nav.account": "Akun",
    "nav.messages": "Pesan",
  },
  en: {
    // Common
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.login": "Login",
    "common.register": "Register",
    "common.email": "Email",
    "common.password": "Password",
    "common.name": "Name",
    "common.upgrade": "Upgrade",
    "common.unlimited": "Unlimited",
    "common.page_of": "Page {{current}} of {{total}}",
    "common.version": "Version",
    "auth.login_subtitle": "Log in to your account",
    "auth.forgot_password": "Forgot Password?",
    "auth.login_failed": "Login failed",
    "auth.google_login_failed": "Google login failed",
    "auth.or_continue": "Or continue with",
    "auth.login_google": "Log in with Google",
    "auth.no_account": "Don't have an account?",
    "auth.register_now": "Register Now",
    "auth.register_title": "Create New Account",
    "auth.register_subtitle": "Start your culinary adventure",
    "auth.full_name": "Full Name",
    "auth.name_placeholder": "Your Name",
    "auth.password_placeholder": "Min. 8 characters",
    "auth.server_failed": "Failed to connect to server",
    "auth.or_register": "Or register with",
    "auth.register_google": "Register with Google",
    "auth.agree_prefix": "By registering, you agree to",
    "auth.agree_suffix": "our",
    "auth.have_account": "Already have an account?",
    "onboarding.skip": "Skip",
    "onboarding.swipe": "Swipe to continue",
    "onboarding.start": "Start",
    "onboarding.slide1.title": "Photo Your Cooking Ingredients",
    "onboarding.slide1.desc": "Confused about what to eat today? Just photo your ingredients and let us prepare the recipe!",
    "onboarding.slide2.title": "Get Instant Recipes",
    "onboarding.slide2.desc": "Get several practical recipe options, complete with calories and nutrition.",
    "onboarding.slide2.highlight": "Soup • Stir-fry • Fried",
    "onboarding.slide3.title": "Cook & Shop Smarter",
    "onboarding.slide3.desc": "Follow the cooking steps and buy missing ingredients through Shopee links.",
    "messages.title": "Messages",
    "messages.search": "Search chats...",
    "messages.cooking_friends": "Cooking Friends",
    "messages.loading_friends": "Loading friends...",
    "messages.no_other_friends": "No other friends",
    "messages.recent_chats": "Recent Chats",
    "messages.loading_chats": "Loading chats...",
    "messages.no_history": "No message history yet.",
    "messages.cooking_friend": "Cooking Friend",
    "messages.no_message": "No messages yet",
    "chat.group_name": "Cooking Group",
    "chat.group": "Group",
    "chat.online": "Online",
    "chat.offline": "Offline",
    "chat.search_messages": "Search messages...",
    "chat.loading": "Loading chat...",
    "chat.no_history": "No chat history yet.",
    "chat.upload_failed": "Failed to upload image",
    "chat.send_failed": "Failed to send message",
    "chat.image_only": "Images only",
    "chat.ready_to_send": "Ready to send",
    "chat.caption_placeholder": "Add a caption... (optional)",
    "chat.message_placeholder": "Type a message...",
    "post.share_title": "Share Your Dish",
    "post.photo": "Dish Photo *",
    "post.upload_photo": "Take or Upload Photo",
    "post.recipe_name": "Dish Name *",
    "post.recipe_placeholder": "Example: Special Fried Rice",
    "post.description": "Description (Optional)",
    "post.description_placeholder": "Tell us about this dish...",
    "post.who_can_see": "Who can see this?",
    "post.public_desc": "Everyone can see",
    "post.friends_desc": "Only friends can see",
    "post.private": "Private",
    "post.private_desc": "Only I can see",
    "post.required": "Recipe name and photo are required!",
    "feedback.choose_category": "Choose a feedback category",
    "feedback.write_feedback": "Write your feedback",
    "feedback.thanks": "Thank you for your feedback!",
    "feedback.title": "Send Feedback",
    "feedback.experience": "How was your experience?",
    "feedback.category": "Category",
    "feedback.detail": "Tell us more",
    "feedback.placeholder": "Write your feedback, suggestion, or bug report here...",
    "feedback.characters": "{{count}}/500 characters",
    "feedback.bug": "Bug Report",
    "feedback.feature": "New Feature",
    "feedback.improvement": "Improvement Suggestion",
    "feedback.other": "Other",
    "not_found.title": "Page Not Found",
    "not_found.desc": "Oops! It looks like the recipe you are looking for is not in our kitchen.",
    "payment.verifying": "Verifying payment...",
    "payment.wait": "Please Wait",
    "payment.order_missing": "Order ID not found",
    "payment.token_missing": "Login token not found. Please log in again.",
    "payment.not_success": "Payment has not succeeded yet",
    "payment.success_message": "Payment successful! Your Premium account is now active.",
    "payment.verify_failed": "Failed to verify payment",
    "payment.active": "Premium Active",
    "payment.view_account": "View Account",
    "payment.failed": "Verification Failed",
    "payment.back_premium": "Back to Premium",
    "scan_history.title": "Scan History",
    "scan_history.search": "Search by ingredient...",
    "scan_history.loading": "Loading history...",
    "scan_history.load_error": "Failed to load scan history.",
    "scan_history.deleted": "Scan history deleted",
    "scan_history.delete_error": "Failed to delete history item",
    "scan_history.cleared": "All history cleared",
    "scan_history.clear_error": "Failed to clear history",
    "scan_history.recipe_options": "{{count}} recipe options",
    "scan_history.empty": "No history found",
    "scan_history.delete_all": "Delete All History",
    "comments.title": "Comments",
    "comments.added": "Comment added successfully!",
    "comments.confirm_delete": "Are you sure you want to delete this comment?",
    "comments.deleted": "Comment deleted successfully!",
    "comments.empty": "No comments yet",
    "comments.be_first": "Be the first to comment!",
    "comments.edit_placeholder": "Edit your comment...",
    "comments.write_placeholder": "Write a comment...",
    "comments.just_now": "Just now",
    "comments.minutes_ago": "{{count}} minutes ago",
    "comments.hours_ago": "{{count}} hours ago",
    "comments.days_ago": "{{count}} days ago",
    "recipe.ai_recommendation": "AI Recommendation",
    "recipe.removed_substitution": "Cancelled replacing {{name}}",
    "recipe.back_original": "Back to the original ingredient",
    "recipe.removed_cookbook": "Removed from Cookbook",
    "recipe.saved_cookbook": "Saved to Cookbook!",
    "recipe.share_success": "Recipe link copied! Share it on WhatsApp",
    "recipe.login_first": "You must log in first",
    "recipe.added_cart": "{{name}} added to cart",
    "recipe.add_shopping_failed": "Failed to add to shopping list",
    "recipe.tweaker_premium": "AI Taste Tweaker is a Premium feature. Upgrade to access it.",
    "recipe.premium_only": "Premium only",
    "recipe.tweaking": "AI is tweaking the recipe...",
    "recipe.tweak_failed": "AI failed to process",
    "recipe.tweaker_desc": "Adjust the recipe to your taste",
    "recipe.tweaker_desc_locked": "Premium - adjust the recipe to your taste",
    "recipe.spicier": "Make It Spicier",
    "recipe.less_sugar": "Make a Lower Sugar Version",
    "recipe.healthier": "Make It Healthier",
    "recipe.no_chili": "Make It Without Chili",
    "recipe.less_spicy": "Make It Less Spicy",
    "recipe.custom_pref": "Or write your own preference",
    "recipe.custom_placeholder": "Example: Make a no-MSG version",
    "recipe.change_recipe": "Change Recipe",
    "recipe.replaced_with": "Replaced with:",
    "recipe.ratio": "Ratio {{ratio}}",
    "recipe.cooking_steps": "Cooking Steps",
    "recipe.step": "Step {{count}}",
    "recipe.ask_ai": "Ask AI Sous-Chef",
    "recipe.ask_example": "\"What can I use instead of oyster sauce?\"",
    "recipe.question_placeholder": "Write your question...",
    "recipe.send": "Send",
    "recipe.selected_rating": "You selected {{rating}} stars",
    "recipe.save_rating": "Save Rating",
    "recipe.confirm_rating": "Are you sure you want to give {{rating}} stars?",
    "recipe.yes_save": "Yes, Save",
    "recipe.rating_saved": "{{rating}} star rating saved",
    "recipe.rating_saved_db": "{{rating}} star rating saved to database!",
    "recipe.rating_save_failed": "Failed to save rating to database: {{message}}",
    "recipe.thanks_feedback": "Thank you for your feedback!",
    "weekly.title": "Weekly Digest",
    "weekly.recipes_made": "Recipes Made",
    "weekly.saved_recipes": "Saved Recipes",
    "weekly.top_ingredients": "Most Used Ingredients",
    "weekly.used_count": "Used {{count}}x",
    "weekly.no_cooking": "No cooking history this week",
    "weekly.achievements": "This Week's Achievements",
    "weekly.no_achievements": "No achievements this week",
    "payment.phone_required": "Enter your phone number",
    "payment.notification_phone": "Payment notification will be sent to this number",
    "payment.select_va_transfer": "Select Transfer to Virtual Account",
    "payment.enter_va": "Enter the VA number above",
    "payment.transfer_amount": "Transfer {{amount}}",
    "payment.save_proof": "Save transfer proof",
    "payment.continue_agree": "By continuing, you agree to",
    "payment.premium_active_package": "Premium Package Active",
    "payment.valid_until": "Valid until May 10, 2026",
    "common.confirm": "Confirm",
    
    // Home Screen
    "home.greeting.morning": "Good Morning",
    "home.greeting.afternoon": "Good Afternoon",
    "home.greeting.evening": "Good Evening",
    "home.scan_prompt": "What would you like to cook today?",
    "home.scan_button": "Scan Ingredients",
    "home.quick_recipes": "Quick Recipes",
    "home.saved_recipes": "Saved Recipes",
    "home.recent_scans": "Recent Scans",
    "home.view_all": "View All",
    "home.ingredients": "ingredients",
    "home.no_saved_recipes": "No saved recipes yet",
    "home.start_scanning": "Start scanning to discover recipes!",
    "home.guest": "Guest",
    "home.daily_search": "Today's searches",
    "home.upgrade_unlimited": "Upgrade for unlimited scans",
    "home.premium_active": "Premium active - unlimited scans",
    "home.scan_card_title": "Photo Your Kitchen Ingredients",
    "home.scan_card_desc": "AI will recognize ingredients and create recipes for you",
    "home.sending_image": "Sending image to server...",
    "home.open_camera": "Open Camera",
    "home.take_photo": "Snap",
    "home.upload": "Upload",
    "home.cooking_gallery": "Cooking Gallery",
    "home.history": "History",
    "home.latest_results": "{{count}} latest results",
    "home.no_scan_history": "No scan history yet",
    "home.recipes_generated": "{{count}} recipes generated",
    "home.public_cooking_count": "{{count}} public dishes",
    "home.friends_cooking_count": "{{count}} dishes from friends",
    "home.my_cooking_count": "{{count}} of your dishes",
    "home.share": "Share",
    "home.public": "Public",
    "home.friends": "Friends",
    "home.me": "Me",
    "home.no_shared_cooking": "No shared dishes yet",
    "home.no_friends_cooking": "No dishes from friends yet",
    "home.no_my_cooking": "You have not shared any dishes yet",
    "home.share_first_cooking": "Share Your First Dish",
    "home.camera_permission_denied": "Camera permission denied",
    "home.camera_not_found": "Camera not found",
    "home.camera_busy": "Camera is being used by another app",
    "home.camera_access_error": "Cannot access camera",
    "home.analyzing_food": "Analyzing food...",
    "home.scan_done": "Scan complete!",
    "home.invalid_backend_response": "Invalid backend response. Please try again.",
    "home.process_image_error": "An error occurred while processing the image",
    "home.daily_limit_reached": "Daily scan limit reached!",
    "home.camera_not_ready": "Camera is not ready",
    "home.image_only": "File must be an image",
    "home.post_shared": "Dish shared successfully!",
    "home.post_deleted": "Dish deleted successfully!",
    "home.privacy_changed": "Privacy changed to {{label}}",
    
    // Scan Result
    "scan.detected_ingredients": "Detected Ingredients",
    "scan.add_ingredient": "Add Ingredient",
    "scan.ingredient_placeholder": "Type ingredient name...",
    "scan.generating": "AI is creating recipes for you...",
    "scan.recipe_recommendations": "Recipe Recommendations",
    "scan.view_recipe": "View Recipe",
    "scan.title": "Scan Result",
    "scan.no_data": "No recipe data was received. Please return to Home.",
    "scan.analyzing": "AI is analyzing...",
    "scan.analyzing_desc": "Recognizing ingredients and crafting the best recipes",
    "scan.no_specific_ingredients": "No specific ingredients were detected automatically.",
    "scan.recipe_options": "Recipe Options For You",
    "scan.ai_recipe": "AI Recipe",
    "scan.calories": "Calories",
    "scan.protein": "Protein",
    "scan.carbs": "Carbs",
    "scan.time": "Time",
    "scan.preparing_recipe": "Preparing Recipe...",
    "scan.save_view_recipe": "Save & View Recipe",
    "scan.save_failed": "Failed to save recipe: {{message}}",
    
    // Recipe Detail
    "recipe.ingredients": "Ingredients",
    "recipe.instructions": "Instructions",
    "recipe.nutrition": "Nutrition Info",
    "recipe.start_cooking": "Start Cooking",
    "recipe.save": "Save",
    "recipe.saved": "Saved",
    "recipe.add_to_shopping": "Add to Shopping",
    "recipe.servings": "Servings",
    "recipe.cook_time": "Cook Time",
    "recipe.difficulty.easy": "Easy",
    "recipe.difficulty.medium": "Medium",
    "recipe.difficulty.hard": "Hard",
    "recipe.calories": "Calories",
    "recipe.protein": "Protein",
    "recipe.carbs": "Carbs",
    "recipe.time": "Time",
    
    // Cooking Mode
    "cooking.step": "Step",
    "cooking.previous": "Previous",
    "cooking.next": "Next",
    "cooking.finish": "Finish",
    "cooking.timer": "Timer",
    "cooking.start_timer": "Start Timer",
    "cooking.complete_title": "Congratulations! 🎉",
    "cooking.complete_message": "You've completed this recipe",
    "cooking.rate_recipe": "Rate Recipe",
    "cooking.back_home": "Back to Home",
    "cooking.mode": "Cooking Mode",
    "cooking.step_of": "Step {{current}} of {{total}}",
    "cooking.completed_toast": "Congratulations! Your dish is finished!",
    "cooking.timer_done": "Timer finished!",
    "cooking.timer_done_desc": "Continue to the next step",
    "cooking.substitution_notice": "Use substitute ingredients for this step:",
    "cooking.ratio": "Ratio {{ratio}}",
    "cooking.ingredients_for_step": "Ingredients for This Step:",
    "cooking.beginner_tips": "Tips for Beginners:",
    "cooking.step_done": "Step complete!",
    "cooking.continue": "Continue",
    "cooking.ask_about_step": "Want to ask about this step?",
    "cooking.question_time": "\"How long should I stir-fry it?\"",
    "cooking.question_substitute": "\"Can I substitute this ingredient?\"",
    
    // Cookbook
    "cookbook.title": "Cookbook",
    "cookbook.all": "All",
    "cookbook.breakfast": "Breakfast",
    "cookbook.lunch": "Lunch",
    "cookbook.dinner": "Dinner",
    "cookbook.snack": "Snack",
    "cookbook.empty": "No saved recipes yet",
    "cookbook.start_exploring": "Start exploring recipes!",
    "cookbook.my_title": "My Cookbook",
    "cookbook.halal": "Halal",
    "cookbook.vegetarian": "Vegetarian",
    "cookbook.vegan": "Vegan",
    "cookbook.favorite": "Favorites",
    "cookbook.newest": "Newest",
    "cookbook.empty_title": "Cookbook Is Empty",
    "cookbook.empty_desc": "Save your favorite recipes here",
    "cookbook.start_scan": "Start Scanning Now",
    "cookbook.confirm_delete": "Are you sure you want to delete this recipe from Cookbook?",
    "cookbook.delete_success": "Recipe deleted successfully!",
    "cookbook.delete_error": "Failed to delete recipe.",
    
    // Shopping List
    "shopping.title": "Shopping List",
    "shopping.add_item": "Add Item",
    "shopping.item_placeholder": "Ingredient name...",
    "shopping.clear_completed": "Clear Completed",
    "shopping.empty": "Shopping list is empty",
    "shopping.add_ingredients": "Add ingredients you need",
    "shopping.buy_all_shopee": "Buy All on Shopee",
    "shopping.buy": "Buy",
    "shopping.shopee_info_title": "Easy Shopping on Shopee",
    "shopping.shopee_info_desc": "Click the \"Buy\" button to search for products directly in the Shopee app. Enjoy free shipping on certain purchases!",
    "shopping.unchecked_count": "{{count}} items not bought yet",
    "shopping.find_recipe": "Find Recipes",
    "shopping.load_error": "Failed to load shopping list",
    "shopping.login_first": "Please log in first",
    "shopping.update_error": "Failed to update",
    "shopping.add_error": "Failed to add ingredient",
    "shopping.deleted": "Item removed from shopping list",
    "shopping.delete_error": "Failed to delete: {{message}}",
    "shopping.connection_error": "Server connection error",
    "shopping.shopee_info_short": "Click the \"Buy\" button to search for products directly in the Shopee app.",
    
    // Account
    "account.title": "Account",
    "account.free_plan": "Free Plan",
    "account.premium_plan": "Premium",
    "account.upgrade": "Upgrade to Premium",
    "account.scans_left": "scans left today",
    "account.unlimited_scans": "Unlimited Scans",
    "account.edit_profile": "Edit Profile",
    "account.dietary_preferences": "Dietary Preferences",
    "account.scan_history": "Scan History",
    "account.settings": "Settings",
    "account.send_feedback": "Send Feedback",
    "account.help": "Help & Support",
    "account.logout": "Logout",
    "account.guest": "Guest",
    "account.current_plan": "Current Plan",
    "account.active_until": "Active until {{date}}",
    "account.your_stats": "Your Statistics",
    "account.scan": "Scans",
    "account.recipes": "Recipes",
    "account.cooking": "Dishes",
    "account.change_preferences": "Change Preferences",
    "account.light_mode": "Light Mode",
    "account.dark_mode": "Dark Mode",
    "account.name_placeholder": "Your Name",
    "account.stats_error": "Failed to fetch statistics. Please try again.",
    "account.logout_success": "Logged out successfully",
    "account.name_limit_error": "You have already changed your name once. Upgrade to Premium for unlimited name changes!",
    "account.name_empty": "Name cannot be empty",
    "account.name_changed": "Name changed successfully",
    "account.name_changed_free": "Name changed successfully. You cannot change it again unless you upgrade to Premium.",
    "account.confirm_name_title": "Confirm Name Change",
    "account.confirm_name_premium": "Are you sure you want to change your name?",
    "account.confirm_name_free": "Are you sure you want to change your name? As a free user, you can only change your name once.",
    "account.confirm_change": "Yes, Change",
    
    // Settings
    "settings.title": "Settings",
    "settings.notifications": "Notifications",
    "settings.recipe_recommendations": "Recipe Recommendations",
    "settings.shopping_reminder": "Shopping Reminder",
    "settings.weekly_digest": "Weekly Digest",
    "settings.promotions": "Promotions & Offers",
    "settings.language": "Language",
    "settings.indonesian": "Bahasa Indonesia",
    "settings.english": "English",
    "settings.data_privacy": "Data & Privacy",
    "settings.auto_save": "Auto Save",
    "settings.export_data": "Export Data",
    "settings.delete_account": "Delete Account",
    "settings.help_support": "Help & Support",
    "settings.help_center": "Help Center",
    "settings.terms": "Terms & Conditions",
    "settings.privacy": "Privacy Policy",
    "settings.app_preferences": "App Preferences",
    "settings.recipe_recommendations_desc_short": "Receive daily recipe suggestions",
    "settings.shopping_reminder_desc_short": "Shopping list notifications",
    "settings.weekly_digest_desc_short": "Your weekly statistics",
    "settings.promotions_tips": "Promotions & Tips",
    "settings.promotions_tips_desc": "Offers and cooking tips",
    "settings.language_desc_short": "Choose the app language",
    "settings.auto_save_recipe": "Auto-save Recipes",
    "settings.auto_save_recipe_desc": "Automatically save viewed recipes",
    "settings.export_data_desc_short": "Download all your data",
    "settings.backup_data": "Backup Data",
    "settings.backup_data_desc": "Save data to cloud",
    "settings.clear_cache": "Clear Cache",
    "settings.clear_cache_desc": "Clear temporary data",
    "settings.help_center_desc_short": "FAQ and guides",
    "settings.terms_desc_short": "Read terms of use",
    "settings.privacy_desc_short": "Learn about your privacy",
    "settings.danger_zone": "Danger Zone",
    "settings.danger_desc": "This action is permanent and cannot be undone.",
    "settings.export_success": "Data exported successfully",
    "settings.delete_coming_soon": "Delete account feature is coming soon",
    "settings.contact_support": "Contact support for help",
    "settings.backup_success": "Backup created successfully",
    "settings.cache_cleared": "Cache cleared successfully",
    "settings.weekly_enabled": "Weekly digest enabled!",
    "settings.weekly_enabled_desc": "Click to view a sample digest",
    "settings.view": "View",
    
    // Premium
    "premium.title": "Upgrade to Premium",
    "premium.subtitle": "Enjoy full features of SnapChef AI",
    "premium.monthly": "Monthly",
    "premium.yearly": "Yearly",
    "premium.save": "Save 40%",
    "premium.per_month": "/month",
    "premium.per_year": "/year",
    "premium.start_trial": "Start 7-Day Free Trial",
    "premium.subscribe": "Subscribe",
    "premium.feature.scans": "Unlimited Scans",
    "premium.feature.recipes": "Save Unlimited Recipes",
    "premium.feature.rename": "Unlimited Rename",
    "premium.feature.premium_recipes": "Access Premium Recipes",
    "premium.feature.support": "Priority Customer Support",
    "premium.feature.ad_free": "Ad-Free Experience",
    "premium.hero_title": "SnapChef Premium",
    "premium.hero_desc": "Enjoy unlimited cooking with smarter AI",
    "premium.already_premium": "You are already Premium!",
    "premium.not_logged_in": "You are not logged in",
    "premium.price": "Rp 49,000",
    "premium.payment_via": "Easy payment via Midtrans",
    "premium.no_daily_limit": "No daily scan limits",
    "premium.chat_title": "Premium AI Sous-Chef Chat",
    "premium.chat_desc": "Unlimited Q&A with AI",
    "premium.taste_title": "AI Taste Tweaker",
    "premium.taste_desc": "Adjust recipes to your taste (spicy, diet, etc.)",
    "premium.vision_title": "AI Vision Advanced",
    "premium.vision_desc": "More accurate and faster ingredient detection",
    "premium.exclusive_recipes": "Exclusive Recipes",
    "premium.exclusive_recipes_desc": "Access thousands of premium recipes",
    "premium.process": "Processing...",
    "premium.upgrade_now": "Upgrade Now",
    "premium.already_button": "Already Premium",
    "premium.payment_methods": "Payment Methods",
    "premium.package_comparison": "Plan Comparison",
    "premium.daily_scan": "Daily Scans",
    "premium.free_scan": "3 scans/day",
    "premium.limited": "Limited",
    "premium.disclaimer_1": "By upgrading, you agree to",
    "premium.disclaimer_2": "our",
    "premium.cancel_anytime": "Subscription can be cancelled anytime",
    "premium.login_required": "You must log in first!",
    "premium.transaction_failed": "Failed to create transaction",
    "premium.payment_open_failed": "Failed to open Midtrans payment",
    
    // Navigation
    "nav.home": "Home",
    "nav.cookbook": "Recipes",
    "nav.shopping": "Shopping",
    "nav.account": "Account",
    "nav.messages": "Messages",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem("snapchef_language");
    return saved || "id";
  });

  useEffect(() => {
    localStorage.setItem("snapchef_language", language);
  }, [language]);

  useEffect(() => {
    const token = getStoredToken();
    if (!token) return;

    const user = JSON.parse(localStorage.getItem("user") || "{}");
    if (!user?.id) return;

    fetch("http://localhost:3000/api/auth/users/" + user.id, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ preferredLanguage: language }),
    }).catch(() => undefined);
  }, [language]);

  const setLanguage = (lang) => {
    setLanguageState(lang);
  };

  const t = (key, values = {}) => {
    const template = translations[language]?.[key] || translations.id?.[key] || key;
    return Object.entries(values).reduce(
      (text, [name, value]) => text.replaceAll(`{{${name}}}`, String(value)),
      template
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
